apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  workspaces:
    - name: workspace
  steps:
    - name: cleanup
      image: busybox
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/workspace/*

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: python:3.9-slim
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        pip install nose
        nosetests
